target-sample:; @true
target-src/cmp:; @true
target-src/coap:; @true
target-src/cota:; @true
target-src/dm:; @true
target-src/fota:; @true
target-src/http:; @true
target-src/log:; @true
target-src/mqtt:; @true
target-src/ota:; @true
target-src/platform:; @true
target-src/sdk-tests:; @true
target-src/shadow:; @true
target-src/subdev:; @true
target-src/system:; @true
target-src/tfs:; @true
target-src/tls:; @true
target-src/utils:; @true
